### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by munirusman** [microsoft/vs-pty.net#16]
Is vs-pty.net published as a NuGet package or a compiled library?

**Comment by javierdlg** [comment]
It isn't publicly available as a NuGet package as of today, but you can build it as a nuget package by running `msbuild \t:pack .\Pty.Net.sln` which should compile a nuget package for you.

**Comment by RHamers** [comment]
Hey. I'm unable to build this. There are missing nuget packages. Could you help me to get the binaries so they can be used and implemented? :) Thank you.

**Comment by javierdlg** [comment]
@RHamers we've moved this to an internal repository due to some limitations with github repos and our internal pipelines. Regardless, I've uploaded the Pty.Net NuGet to our public preview feed [msft_consumption](https://dev.azure.com/azure-public/vside/_artifacts/feed/msft_consumption). Simply add that feed as a NuGet source and you can then add the package as a package reference to your project.

You can also manually download it from here:
https://dev.azure.com/azure-public/vside/_artifacts/feed/msft_consumption/NuGet/Pty.Net/overview/0.3.94-pre

**Comment by RHamers** [comment]
Thank you! :) I'll give it a go.

**Comment by RHamers** [comment]
Hey, I got the Nuget package to work but I'm trying to wrapp my head around on how to use it exactly. When I for example start a bash terminal on widows I get all these ANSI VT100 encoded strings back. What's the best way to deal with this? I would like to use vs-pty to implement an integrated terminal in my application so I basically just need to interface to talk to and pass I/O back and forth. Thx!

**Comment by RHamers** [comment]
Hey, never mind :) I found [this](https://github.com/microsoft/vs-pty.net/blob/main/src/Pty.Net.Tests/PtyTests.cs) unit test in the package which made things clear :) I do have another followup question though: is there a nice way to send ascii based characters across to the console? Like `Enter=0x0D` or `Ctrl+X=0x18`?
