### ISSUE TITLE
What is the actual state of the project?

### ISSUE THREAD

**Issue by PhonicUK** [microsoft/vs-pty.net#29]
The package appears unlisted in NuGet, there's no documentation or examples, the version that *is* in NuGet is from 2018, and there don't appear to be any substantive code changes for over a year.

Are there any major reasons not to use this project? Or is it essentially deprecated?

**Comment by javierdlg** [comment]
Hi Phonic,
We implemented this PTY project to support our integrated terminal within Visual Studio. Regardless, we kept this project open source since it is a fork of another open source project. This repo is not deprecated or abandoned and we are actively fixing issues as they come up.

We don't publish a Pty.Net NuGet package since we only use it internally but you are free to clone and build your own bits for your personal projects. 

Hopefully that answers your questions! Lmk if you need more details.

**Comment by PhonicUK** [comment]
Gotcha - what project is this originally a fork of?

**Comment by javierdlg** [comment]
My bad, we didn't fork this repository.
